language: java
sudo: true
before_script:
  - chmod +x mvnw
before_install:
 - chmod +x gradlew
jdk:
  - oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V      
