version: '3'

volumes:
  data:

services:

 mysql-dev:
    image: mysql:8.0.2
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: marinasync
    ports:
      - "3308:3306"
    volumes:
      - "data:/opt/marinasync/mysql"

 client: 
    image: mysql:8.0.2
    depends_on:
      - mysql-dev
    command: mysql -uroot -ppassword -hmysql-dev marinasync
    volumes:
      - "data:/opt/marinasync/mysql"
